### ISSUE TITLE
cargo build --release using latest code

### ISSUE THREAD

**Issue by stardustman** [crumblingstatue/hexerator#30]
```bash
stardust@MacBook-Pro ~/git-repos/hexerator (main)
$ git pull             
Already up to date.
stardust@MacBook-Pro ~/git-repos/hexerator (main)
$ cargo build --release
   Compiling hexerator v0.1.0 (/Users/stardust/git-repos/hexerator)
error[E0308]: mismatched types
   --> src/app.rs:544:10
    |
537 |     pub(crate) fn load_proc_memory(
    |                   ---------------- implicitly returns `()` as its body has no tail or `return` expression
...
544 |     ) -> anyhow::Result<()> {
    |          ^^^^^^^^^^^^^^^^^^ expected enum `Result`, found `()`
    |
    = note:   expected enum `Result<(), anyhow::Error>`
            found unit type `()`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `hexerator` due to previous error
stardust@MacBook-Pro ~/git-repos/hexerator (main)
$ rustc --version
rustc 1.65.0-nightly (95a992a68 2022-09-16)
```

**Comment by crumblingstatue** [comment]
Hi! Currently Mac Os is not supported. I'm looking for a Mac Os developer who can help maintain Hexerator for Mac Os, as I don't have a Mac Os system to test on.

**Comment by crumblingstatue** [comment]
That being said, one thing I can try for now is to simply disable the process memory functionality for Mac Os. Hopefully the rest of the functionality will work.

**Comment by crumblingstatue** [comment]
For now I'm gonna focus on porting to wgpu and winit, so it will be easier to set up CI for Mac OS, so testing for it will be easier.

However, if you're feeling adventurous, you could try replacing the erroring parts on Mac Os with panics.
That would at least make most of the functionality work on OS X, excluding process memory editing.

The task would be to add `#[cfg(target_os = "macos")]` where appropriate, and add `todo!("Implement for Mac OS");`, or similar.

**Comment by AliSajid** [comment]
I have created a pull request #35 to add nominal support for macos. I'm not an expert but have a macbook and drive to learn so will be able to contribute

**Comment by AliSajid** [comment]
@crumblingstatue Maybe close this?

**Comment by crumblingstatue** [comment]
I guess so.
