### ISSUE TITLE
Compilation Issues with latest nightly

### ISSUE THREAD

**Issue by benibr** [crumblingstatue/hexerator#40]
Thanks for writing this tool!

Since I had some issues while trying to compile hexerator with the latest Rust version I'd like to suggest that instead of writing just `channel=nightly` to the `rust-toolchain.toml` each commit or each realease should come with a specific nightly-date version that's able to compile correcty.

For example with Rust nightly-2022-11-07 I cannot compile hexerator 0.1.0 due to https://github.com/rust-lang/rust/issues/93050

I pinned the Rust version to `nightly-2022-09-15` and it works but I had to manually fix package builds
https://aur.archlinux.org/packages/hexerator

**Comment by crumblingstatue** [comment]
Hi!
Thank you for making an AUR package for Hexerator!
I released [v0.1.1](https://github.com/crumblingstatue/hexerator/releases/tag/v0.1.1), which should pin the nightly to the suggested version. Let me know if this fixed your issue!

**Comment by crumblingstatue** [comment]
There is a new AUR package up with the new version, so I'm going to consider this issue fixed.
