### ISSUE TITLE
Compilation error on macOS.

### ISSUE THREAD

**Issue by engstad** [crumblingstatue/hexerator#44]
I get (`cargo build --release`):
```
The following warnings were emitted during compilation:

warning: CSFML/src/System/Clock.cpp:1:10: fatal error: 'SFML/System/Clock.hpp' file not found
warning: #include <SFML/System/Clock.hpp>
warning:          ^~~~~~~~~~~~~~~~~~~~~~~
warning: 1 error generated.

error: failed to run custom build command for `sfml v0.20.0`
```
Can you check for `sfml`?

**Comment by engstad** [comment]
I should note that I got past this using:
```
$ brew install sfml csfml
```

**Comment by engstad** [comment]
In terms of macOS support, perhaps you could use: https://github.com/rbspy/read-process-memory, instead of spinning your own?

**Comment by crumblingstatue** [comment]
Yeah, I think the mac os support is completely broken.
I don't have a Mac, so I can't test anything Mac related.
I'm looking for a Mac developer/maintainer who can do that.

**Comment by trumank** [comment]
> I should note that I got past this using:
> 
> ```
> $ brew install sfml csfml
> ```
I also had to set these env vars after installing SFML via brew:
```
export SFML_INCLUDE_DIR=/opt/homebrew/include
export SFML_LIBS_DIR=/opt/homebrew/lib
```

**Comment by crumblingstatue** [comment]
Current version doesn't require SFML to be installed, so I'm closing this issue.
