### ISSUE TITLE
Jump not working when inside a process

### ISSUE THREAD

**Issue by at-manos** [crumblingstatue/hexerator#46]
Jump inside ctrl+J and bookmark menu (hyperlink and button) are not working inside a process. Ctrl+J jump sets the cursor to 0, bookmark menu buttons do nothing at all. Region goto hyperlinks work, and so do the ones inside the find menu. 

Hexerator is being run with sudo. Nothing reported inside debug panel.

All of them work in a typical file. 

Built today with rust nightly, would be great to have this functionality! Not sure if it's just my machine.

**Comment by at-manos** [comment]
In case this info is of any use:

Hexerator: 
Version: 0.3.0-dev
Git SHA: VERGEN_IDEMPOTENT_OUTPUT
Commit date: VERGEN_IDEMPO
Build date: 2023-11-20
Target: x86_64-unknown-linux-gnu
Debug: true
Opt-level: 0
Built with rustc: 1.74.0-nightly
System: 
OS: Arch Linux rolling
CPU: Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
Total memory: 15870 MiB
Used memory: 2758 MiB
Available memory: 13112 MiB

**Comment by crumblingstatue** [comment]
These turned out to be two separate bugs, I pushed fixes for both of them.

Thank you for helping test Hexerator! I haven't had much time to play around with it lately.

**Comment by at-manos** [comment]
No problem! Thank you for such a quick fix. I wasn't sure if this would get seen, so thanks for doing such a great job maintaining this project.
